// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderAssignmentEF;

#nullable disable

namespace OrderAssignmentEF.Migrations
{
    [DbContext(typeof(DemoDBContext))]
    partial class DemoDBComtextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OrderAssignmentEF.MasterAllData.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("Email")
                        .HasColumnType("int");

                    b.Property<string>("FirstNAme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.ToTable("customer");
                });

            modelBuilder.Entity("OrderAssignmentEF.MasterAllData.Item", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemQTY")
                        .HasColumnType("int");

                    b.Property<int>("ItemRate")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("item");
                });

            modelBuilder.Entity("OrderAssignmentEF.MasterAllData.Customer", b =>
                {
                    b.HasOne("OrderAssignmentEF.MasterAllData.Customer", null)
                        .WithMany("customer")
                        .HasForeignKey("CustomerID");
                });

            modelBuilder.Entity("OrderAssignmentEF.MasterAllData.Customer", b =>
                {
                    b.Navigation("customer");
                });
#pragma warning restore 612, 618
        }
    }
}
